file_format: "1"
id: trackpadtrackball
name: Trackpad Trackball
type: shield
url: https://github.com/jgreel/wearable_cirque_pim447
requires:
  - pro_micro
  - pimoroni trackball_pim447

features:
  - mouse
  - pointer
siblings:
  - pimtrackball
