manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk-config
      remote: zmkfirmware
      path: zmk-config
      revision: main
  self:
    west-commands: scripts/west-commands.yml
