name: Build ZMK Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install west
        run: |
          python -m pip install --upgrade pip
          pip install west

      - name: Install Zephyr SDK
        run: |
          wget https://github.com/zephyrproject-rtos/toolchain/releases/download/zephyr-sdk-0.16.3/zephyr-sdk-0.16.3-linux-x86_64.tar.gz
          tar -xzf zephyr-sdk-0.16.3-linux-x86_64.tar.gz
          export ZEPHYR_SDK_INSTALL_DIR=$PWD/zephyr-sdk-0.16.3

      - name: Set up Zephyr environment
        run: |
          west init -l zmk-config
          west update
          export ZEPHYR_BASE=$PWD/zephyr
          export PATH=$ZEPHYR_SDK_INSTALL_DIR/sysroots/x86_64-pokysdk-linux/usr/bin:$PATH

      - name: Build ZMK firmware
        run: |
          west build -s zmk/app -d /tmp/build -b nice_nano_v2 -- -DZMK_CONFIG=/tmp/zmk-config/config -DSHIELD=corne_right -DZMK_EXTRA_MODULES='/__w/zmk-config/zmk-config'
