on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Zephyr SDK
        uses: zephyrproject-rtos/setup-zephyr-sdk@v1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install west
          west update
          west build -s zmk/app -d /tmp/build -b nice_nano_v2 -- -DZMK_CONFIG=/tmp/zmk-config/config -DSHIELD=corne_right -DZMK_EXTRA_MODULES='/__w/zmk-config/zmk-config'

